# Generated by Django 4.2.3 on 2023-07-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('url', models.TextField()),
                ('imagen', models.ImageField(default='null', upload_to='', verbose_name='miniature')),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('nombre', models.TextField()),
                ('poblacion', models.TextField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
